apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: k8microservice-svc
  namespace: default 
  labels:
    app: k8Microservice
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: k8Microservice
  type: ClusterIP